# Display Handler
DEFAULT_DISPLAY_WIDTH = 128
DEFAULT_DISPLAY_HEIGHT = 64
CENTRAL_ANCHOR_POINT = (0.5, 0)
DEFAULT_DISPLAY_BRIGHTNESS = 0.3
DEFAULT_KEYBOARD_BRIGHTNESS = 0.2

# MacroPad
KEYBOARD_LAYOUT = None
KEYCODE = None

# Keyboard Handler
LONG_DELAY_MS = 500

# Action Queue
DEFAULT_ACTION_DELAY_MS = 10

# Macro Board Handler
MACRO_FOLDER = '/macros'
DEFAULT_NONE_COLOR = 0x000000
DEFAULT_COLOR_SELECTED_ROTARY_ACTION = 0xFFFFFF
DEFAULT_COLOR_ONE_TIME_ACTION = 0xFFBA13
DEFAULT_COLOR_KEEP_PRESSED = 0x13FFBA
DEFAULT_COLOR_UNTIL_NEXT_PRESS = 0xBA13FF
DEFAULT_COLOR_PRESSED = 0x0F0F0F
