# Display Handler
DEFAULT_DISPLAY_WIDTH = 128
DEFAULT_DISPLAY_HEIGHT = 64
CENTRAL_ANCHOR_POINT = (0.5, 0)
DEFAULT_DISPLAY_BRIGHTNESS = 0.3
DEFAULT_KEYBOARD_BRIGHTNESS = 0.2

# MacroPad
KEYBOARD_LAYOUT = None
KEYCODE = None

# Keyboard Handler
LONG_DELAY_MS = 500

# Action Queue
DEFAULT_ACTION_DELAY_MS = 10

# Macro Board Handler
MACRO_FOLDER = '/macros'
