# Display Handler
DEFAULT_DISPLAY_WIDTH = 128
DEFAULT_DISPLAY_HEIGHT = 64
CENTRAL_ANCHOR_POINT = (0.5, 0)
LOW_BRIGHTNESS = 0.1
HIGH_BRIGHTNESS = 0.5

# MacroPad
KEYBOARD_LAYOUT = None
KEYCODE = None

# Keyboard Handler
LONG_DELAY_MS = 500
